### ISSUE TITLE
edb installation failed for pgadmin when username is Chinese under c:\user

### ISSUE THREAD

**Issue by rdczhzq** [EnterpriseDB/edb-installers#106]
When I tried to use postgresql-16.2-1-windows-x64 to install on a window laptop. I got the following error message and installation aborted.

![image](https://github.com/EnterpriseDB/edb-installers/assets/168157852/5d2faa3e-ad91-4d35-a4e5-9744a43a9e57)

After using another not edb installation:pgadmin4-8.5-x64.exe, I successfully installed pgadmin by changing the default install path from c:\user\老王 to all English character path.

**Comment by sandeep-edb** [comment]
committed the fix on all supported branches. the fix will be available in this week's minor updates

**Comment by rdczhzq** [comment]
Hi Sandeep,

Thanks for your quick feedback and effort.

Best regards,
Joe



***@***.***
 
From: Sandeep Thakkar
Date: 2024-05-07 13:45
To: EnterpriseDB/edb-installers
CC: rdczhzq; Author
Subject: Re: [EnterpriseDB/edb-installers] edb installation failed for pgadmin when username is Chinese under c:\user (Issue #106)
committed the fix on all supported branches. the fix will be available in this week's minor updates
