### ISSUE TITLE
How to setup poll time options through pgAgent installer

### ISSUE THREAD

**Issue by michelle0809** [EnterpriseDB/edb-installers#120]
PostgreSQL version: 13.13
pgAgent version: 4.2.2-1

I'm trying to add -t option (poll time interval in seconds) when installing pgAgent Service through EDB pgAgent installer.

I have tried the following
1. `edb_pgagent_pg13.exe --mode unattended --pgpassword 1234 --systemuser postgres --systempassword 1234 -t 60`
2. `edb_pgagent_pg13.exe --mode unattended --pgpassword 1234 --systemuser postgres --systempassword 1234 --optionfile "C:\Users\Administrator\Desktop\optionfile.txt"`
and the content of  optionfile.txt is '-t 60'.

Neither method works.

How do I make the pgAgent Service command after installation include the -t option?
The picture below is the result I expect
![image](https://github.com/EnterpriseDB/edb-installers/assets/71964831/66d5c3f4-aa6c-4d44-94e0-06209b9c251f)

**Comment by dpage** [comment]
It is not possible to set the poll time through the installer.
