### ISSUE TITLE
%PATH%

### ISSUE THREAD

**Issue by Dmole** [EnterpriseDB/edb-installers#123]
**Describe the bug**

On Windows Backup and Restore exit with no error message.

**To Reproduce**

1. After using the installer linked from https://www.postgresql.org/download/windows/
2. Run pgAdmin 4
3. Create a database
4. Attempt to Backup from or Restore to the database
5. See it error with no message or logs

**Expected behavior**

Backup / Restore should just work.
If they fail, pgAdmin 4 should log why.

**Error message**

Process failed
No longs available
Exit code 3221225781

**Desktop (please complete the following information):**
 - OS: Windows 10 (server 2022)
 - pgAdmin 4 Version: 7.8

**Additional context**

If the shown command is pasted into cmd.exe the following error is shown:

The code execution cannot proceed because libzstd.dll was not found. 

echo  %errorlevel%
-1073741515

Adding the PostgreSQL bin folder to the windows %PATH% fixes the issue.

- EnterpriseDB should set the %PATH%
- PGAdmin4 should show error messages: https://github.com/pgadmin-org/pgadmin4/issues/7466

**Comment by sandeep-edb** [comment]
@Dmole what version of the PostgreSQL installer have you installed?

**Comment by Dmole** [comment]
postgresql-16.3-1-windows-x64.exe

**Comment by agarwal-kritika** [comment]
@Dmole With postgresql-16.3-1-windows-x64.exe , pgAdmin v8.7 is bundled and this issue is not reproducible from our side.

**Comment by dpage-edb** [comment]
We're not going to be setting %PATH%; we learned 15+ years ago that that is generally a very bad idea which can lead to all manner of confusing and broken behaviour if (for example) there are multiple version of PostgreSQL installed.
