### ISSUE TITLE
Include pgvector Extension in EDB Installers

### ISSUE THREAD

**Issue by anthonydb** [EnterpriseDB/edb-installers#124]
I understand that EDB can't go wild and include all sorts of extensions with its PostgreSQL installers, but [pgvector](https://github.com/pgvector/pgvector) is getting a lot of attention these days and would be welcomed. Althought [installation](https://github.com/pgvector/pgvector?tab=readme-ov-file#installation) would be straightforward for intermediate/expert users, I work with a lot of beginners who would find installation difficult.

Thanks for considering!

**Comment by dpage-edb** [comment]
We intentionally don't add extensions to the PostgreSQL installers as there are so many of them (many of which have gained and lost popularity over the years). We have the StackBuilder infrastructure to allow extension and add-on authors to distribute and maintain their own releases in a way that allows easy installation for end users.

**Comment by anthonydb** [comment]
Thanks for the reply. What is the procedure for a developer to add their extension to StackBuilder?

**Comment by dpage** [comment]
They need a "single file" installer, e.g. a .exe or .msi on Windows, or a zipped .pkg or .mpkg installer bundle on macOS. On Windows, the installer needs to record the version number of the installed version in the registry, under a path that includes the PostgreSQL version it's compatible with (for an extension - apps typically don't need that). e.g.

HKLM\Software\Acme\MyApp\pg16\Version = 1.0

On macOS, the version should be recorded in /etc/postgres-reg.ini.

Once any packages are available for download, the relevant metadata can be added to the catalogue, by request to the PostgreSQL web team, so they show up as an option in StackBuilder.
