### ISSUE TITLE
Can I get a file hash of the postgresql-15.8-1-windows-x64.exe installer?

### ISSUE THREAD

**Issue by BeSchu-Hett** [EnterpriseDB/edb-installers#144]
Hello,

our endpoint protection tool reported an issue with the signature of your installer. To be exact: postgresql-15.8-1-windows-x64.exe as of 12.08.2024 14:49.
Can you please provide me with a checksum of the installer so i can verify the file isn't manipulated?

Thanks in advance.

**Comment by agarwal-kritika** [comment]
Hi BeSchu,

Here is the checksum of the installer : 5d59da54ffa5b527f130ac2610ba8b9c

**Comment by BeSchu-Hett** [comment]
Thank you! The checksum is the same, as with our download.
