### ISSUE TITLE
trying to install postgresql 16 on windows 11

### ISSUE THREAD

**Issue by obeejohnkanobi** [EnterpriseDB/edb-installers#147]
get followin warning

psql: error: connection to server at "localhost"(::1), port 5432 failed: server does not support SSL, but SSL was required

I have install SSL, everything is up to date.

**Comment by obeejohnkanobi** [comment]
I run windows 11

**Comment by sandeep-edb** [comment]
hi @obeejohnkanobi do you see this error during installation? what's the complete version of the installer? do you have the existing installation on disk or is it a fresh installation?

**Comment by obeejohnkanobi** [comment]
Hi

Newest version, w11, during installation, the second half, let the
installer install.

Med venlig hilsen

Yahya John Lorenzen




man. 26. aug. 2024 kl. 08.23 skrev Sandeep Thakkar ***@***.***

**Comment by sandeep-edb** [comment]
Glad to know the installation is successful at your end. Closing the ticket
