### ISSUE TITLE
Unable to download using Windows installer

### ISSUE THREAD

**Issue by nishanth1991** [EnterpriseDB/edb-installers#151]
I am getting "Something went wrong' in the next page after clicking on Download installer from the Windows installers page.

URL: https://www.postgresql.org/download/windows/

Path: Homepage > Download > Windows > Download the installer

Screenshot: 
![image](https://github.com/user-attachments/assets/1b3451bf-0ba2-4696-abf3-dfb1d22ce7da)

**Comment by fico13** [comment]
try different browser, or turn off your adblocker if u have it

**Comment by nishanth1991** [comment]
This issue resolved after sometime
