### ISSUE TITLE
ERREUR FATAL

### ISSUE THREAD

**Issue by salomonkoffibi07** [EnterpriseDB/edb-installers#160]
Quand j'ouvre pgAdmin, je reçois une erreur fatale. Comment remédier à ça ?

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\Koffi\AppData\Roaming\pgadmin4\config.json"
Webapp Path: "C:\Program Files\PostgreSQL\15\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\15\pgAdmin 4\web\pgAdmin4.py"

**Comment by sandeep-edb** [comment]
Could you please try with the latest postgresql installer that was made available? hopefully the issue is resolved
