### ISSUE TITLE
Installer download broken with 403 response

### ISSUE THREAD

**Issue by jamiebarrow** [EnterpriseDB/edb-installers#161]
I'm unable to download the installer for Windows, and constantly get a 403 response from the download page.

Seems I am not the only one, cross posting below:
https://github.com/microsoft/winget-pkgs/issues/127503

**Comment by jamiebarrow** [comment]
Is it possible to publish the distributable installers in Github Releases?

**Comment by dpage** [comment]
It appears that winget is using Microsoft's delivery optimisation mechanisms, which are causing downloads to be broken up into 512KB requests, which are then getting rate limited by CloudFront. We've adjusted the rate limiting to try to mitigate this.

**Comment by jamiebarrow** [comment]
Thanks @dpage! I tried it out again on another machine this evening, and I see it did fail at first but on second attempt it succeeded.

I'll let you manage this issue in case you want to keep visibility of it, but if you feel it is "closed" then go ahead ;)

![image](https://github.com/user-attachments/assets/46e1513e-2c61-4c8a-ac77-b1f60cd259fe)

**Comment by dpage-edb** [comment]
Thanks for the update. I'll close this for now, but we'll continue to monitor the situation.

**Comment by GTonehour** [comment]
I attempted `winget install PostgreSQL.PostgreSQL.17` five times, all failed with said error. Three failed immediately, one at 280/342 MB, the other at 266/342 MB. I suggest reopening the issue.
