### ISSUE TITLE
PGAdmin 4 opening as a blank page after installing PostgreSQL 17 on Mac

### ISSUE THREAD

**Issue by gabdelnour** [EnterpriseDB/edb-installers#167]
Hey everyone,

I'm having an issue installing PostgreSQL on my Mac. I'm currently running  macOS Sonoma Version 14.5 and I'm trying to install and run PostgreSQL 17.RC1. After going through the installation process and trying to open PGAdmin 4 the app is opening blank (image attached below)

<img width="1027" alt="Screenshot 2024-09-25 at 5 39 24 PM" src="https://github.com/user-attachments/assets/6da74349-bc86-428f-ab6b-7932bae8cad5">

Some context, when I first installed the app I was getting an Error when opening PGAdmin 4 saying: Configuration error, couldn't connect to server. Since then I've uninstalled and installed PostgreSQL several times and I've deleted the data folder after the uninstallations. I've try with version 16 and version 17.

Please help!

**Comment by sandeep-edb** [comment]
Hi,
The issue should be fixed in the PostgreSQL 17.0 that is released yesterday. Could you please try that?
