### ISSUE TITLE
Spatial Extension Stack Builder 4.2.1

### ISSUE THREAD

**Issue by jbcoop** [EnterpriseDB/edb-installers#171]
Is the Spatial Extension no longer an option in the app builder of Postgres (Ver. 17)? I cant use postgis.

thanks

![Stack_Builder 4 2 1](https://github.com/user-attachments/assets/e6d13ae5-7ce7-4cdf-a36c-727ac3d648e3)

**Comment by sandeep-edb** [comment]
That should be available when the extension packages are available for download. They are not ready yet. Is this windows or macOS?

**Comment by msanchezaparicio** [comment]
I have the same problem. In my case on Windows.

**Comment by sandeep-edb** [comment]
EDB doesn't prepare windows spatial installer though. I'm not who does it.

**Comment by msanchezaparicio** [comment]
It is resolved. PostGIS 3.5 now available for Postgre.
