### ISSUE TITLE
installer cannot be executed as "nt-autorität\system"

### ISSUE THREAD

**Issue by neeral85** [EnterpriseDB/edb-installers#173]
as mentioned here [BUG #18615: installer cannot be executed as "nt-autorität\system"](https://www.postgresql.org/message-id/18615-4bc7fdf205fa1a83%40postgresql.org) it looks like installer does set incorrect file permission on temp folder.

16.2 installer works, 16.4 installer does not work if executed as "nt-autorität\system"

significant difference we noticed is temp folder permission with 16.2 get set for "SYSTEM" while permission with 16.4 get set for "DEVICENAME"

**Comment by tpblpb** [comment]
Hello, same problem for me, installation of this software is made with "wapt" and "SYSTEM" user for my company.
I havent got issues with older version "15.2-1" and "16.2-1".
The version "16.4-1" and i also tried "17.0-1" doens't install (the installation stop when unzip I think). I have the error:
Output:Erreur lors de la copie du fichier de archive C:/ProgramData/postgresql-16.4-1-windows-x64.exe compressée à C:/Windows/Temp/postgresql_installer_0308150fde/prerun_checks.vbs
:Impossible d'écrire vers la destination
Abort
error.writing.temp
Debug file written.

or:
Output:Erreur d'écriture du fichier C:/Windows/Temp/postgresql_installer_938cd760d7/temp_check_comspec.bat

I've tried all the posibilities but I cannot find any solutions. I think that the issues comes from the administrator priviliged required for the installation, but, with wapt the installation is made by : autorite nt\système.
I would like to have news for this issue.
Regards

**Comment by sandeep-edb** [comment]
Hi,
We're checking already but unable to find the solution to this specific case yet and working on it

**Comment by moerwald** [comment]
+1 for this. I've the same problem

**Comment by neeral85** [comment]
same issue again with 16.5!
As it was working with 16.1 what is the challenge to identify the difference with the installer?

**Comment by sandeep-edb** [comment]
I made a small change in the installer to allow the non-ascii characters in the system username and uploaded the "test/snapshot" (not for production) installer postgresql-17.2-0.0snapshot12069192100.994.1.10c136e.1-windows-x64 to https://enterprisedb.sharefile.com/f/fo423619-ac6b-4868-ac4c-b2e3def6e3b0

If you could try installing and confirm how it went? Please note there is no handling of non-english service account names included yet. Also, during installation, the Info dialogues will appear to show the name and the SID of the user running the installer. Please confirm if it's correct.

If you have any questions please let me know.

**Comment by sandeep-edb** [comment]
The PostgreSQL 17.2-2, 16.6-2, 15.10-2 are available for download. These installers include a fix for system installation issue.

**Comment by neeral85** [comment]
I can confirm the issue got fixed. Thanks! 👍

**Comment by tpblpb** [comment]
It works, thank you very much !!
