### ISSUE TITLE
Failure to run backup in PG Admin 4 with PostgreSQL 17 - windows 11

### ISSUE THREAD

**Issue by png-bebig** [EnterpriseDB/edb-installers#176]
The log show an obvious reason:
`pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.0; pg_dump version: 16.4`

I did a workaround by overwriting the pg_dump.exe from the folder `C:\Program Files\PostgreSQL\17\bin` to the folder `C:\Program Files\PostgreSQL\17\pgAdmin 4\runtime` and it works.
This is because the former has the correct build version number of 17 while the latter has the older version number of 16.4.

It would be very helpful if you could fix this issue. Thanks.

**Comment by sandeep-edb** [comment]
Thank you for the report. We will look into it and fix in the next release

**Comment by phpdev-irtech** [comment]
You save my life 💯

**Comment by Manika-EDB** [comment]
Hi,
This bug is fixed in the upcoming minor releases on 14th Nov'24.

**Comment by Manika-EDB** [comment]
Hi,
This bug is fixed in the upcoming minor releases on 14th Nov'24.
