### ISSUE TITLE
Postgresql 17 Installation Error on Windows 11

### ISSUE THREAD

**Issue by landym02** [EnterpriseDB/edb-installers#178]
Not much to add, but I can't get Postgresql 17 to install on a Windows 11 machine.  The install file is postgresql-17.0-1-windows-x64.exe.

Attached is the debug file that was created.  
[installbuilder_debug_21768.zip](https://github.com/user-attachments/files/17399535/installbuilder_debug_21768.zip)

Here is the error message

![image](https://github.com/user-attachments/assets/9200f516-3f15-4f4d-9e55-f39fb46fa9be)

**Comment by sandeep-edb** [comment]
Can you also share the installation log file that must have generated in system temp location

**Comment by landym02** [comment]
[install-postgresql.zip](https://github.com/user-attachments/files/17413668/install-postgresql.zip)

Here are the other log files I found.

**Comment by sandeep-edb** [comment]
Thanks, It's odd behaviour. What's your Windows version? Also, if you can run the installer exe with `--debugtrace debug.txt` and share the debug file?

**Comment by sandeep-edb** [comment]
closing the issue. if the issue persists with the latest run, then please log a new issue.
