### ISSUE TITLE
PG 15 - Language Pack - create extension plperl Error

### ISSUE THREAD

**Issue by firtree-23** [EnterpriseDB/edb-installers#180]
Environment:  "PostgreSQL 15.5, compiled by Visual C++ build 1914, 64-bit" on a Win2019 Server.

We installed the edb languagepack using the stackbuilder installer and configured env variables as recommended. Unfortunately we get errors  when trying to install plplerl by using "CREATE EXTENSION plperl" 

The logfile contains errors like this:
"...Util.c: loadable library and perl binaries are mismatched (got first handshake key 0000000012700080, needed 0000000012600080)"

It seems, that there is a mismatch between expected and installed perl version. I'd be very glad to get a hint how to solve this problem.

**Comment by sandeep-edb** [comment]
Could you share the languagepack installer filename that you installed?

**Comment by firtree-23** [comment]
![grafik](https://github.com/user-attachments/assets/0f5b32e2-e23e-4055-8d71-8b48f4b55db4)

**Comment by firtree-23** [comment]
![grafik](https://github.com/user-attachments/assets/ece235cf-ecf3-48d0-aa6f-5dae33bc0787)

**Comment by sandeep-edb** [comment]
this must be fixed in the next week maintenance release

**Comment by firtree-23** [comment]
Very glad to hear this. Thanks a lot.

**Comment by agarwal-kritika** [comment]
This issue is fixed in today's release.
