### ISSUE TITLE
Language Pack Missing in PostgreSQL 17 

### ISSUE THREAD

**Issue by anthonydb** [EnterpriseDB/edb-installers#184]
Doing a fresh install of PostgreSQL 17 on Windows 11, and the EDB Language Pack is not present in StackBuilder. Is this a permanent change or will you be adding it back in? Thanks.

**Comment by sandeep-edb** [comment]
Hi,
This is expected change on Windows. There will be no more LanguagePack installer and you need to get the upstream binaries. Please refer the installation notes installed at $installdir/doc/installation-notes.html

**Comment by anthonydb** [comment]
Thanks. For what it's worth, the installation notes could be a little more explicit about how to set the Python path using System variables rather than user variables.
