### ISSUE TITLE
PostgreSQL cannot be opened on mac Sequoia 15.1.

### ISSUE THREAD

**Issue by linsaw** [EnterpriseDB/edb-installers#185]
_LSOpenURLsWithCompletionHandler() failed with error -54.
![QQ20241031-125258](https://github.com/user-attachments/assets/8abf6d14-ac54-48b0-8902-63d58d2d7784)

**Comment by linsaw** [comment]
mackbook is Apple M2

**Comment by lsharaf** [comment]
same issue here, macbook is Apple M3

**Comment by linsaw** [comment]
> same issue here, macbook is Apple M3

It may be that the built-in pgAdmin4 in PostgreSQL is causing the issue. You can download a separate pgAdmin4 from the website at [https://www.pgadmin.org/download](url)

**Comment by lsharaf** [comment]
worked, thanks

**Comment by dcatmakas** [comment]
it's worked, thank you.

**Comment by TH1622EE** [comment]
@linsaw thank you that worked for me as well on a Mac Studio Ultra M2

**Comment by Cristian2529** [comment]
I have the same problem, my Mac is M3 pro and Sequoia 15.1, could you help me

**Comment by ayushrameja** [comment]
had the same problem while installing PostgreSQL 17, Please install pgadmin4 separately or install DBeaver as an alternative.

pgAdmin4: [https://www.pgadmin.org/download/pgadmin-4-macos/](https://www.pgadmin.org/download/pgadmin-4-macos/)
DBeaver: [https://dbeaver.io/download/](https://dbeaver.io/download/)

**Comment by Djakaridja** [comment]
> https://www.pgadmin.org/download/pgadmin-4-macos/

Worked for me on apple M3

**Comment by Doublefire-Chen** [comment]
Same issue for me.
<img width="372" alt="Screenshot 2024-11-13 at 16 08 43" src="https://github.com/user-attachments/assets/def03942-3cc0-4103-a65c-061d5a802f06">
Environment:
Version: ```postgresql-16.4-1-osx.dmg``` and ```postgresql-17.0-1-osx.dmg```
Hardware: ```Macbook Pro 2020 intel chip```
OS: ```macOS Sequoia 15.1 (24B83)```

**Comment by Blackork1** [comment]
Hey guys, for me this worked: 
open this page: https://www.pgadmin.org/download/pgadmin-4-macos/
select pg-admin versin, for me the most current version was [pgAdmin 4 v8.12],
click on it, and then select [pgadmin4-8.12-arm64.dmg] file.
Download it and double click and drag inside the application folder. Now you should start the programm.

**Comment by moharanasudipt** [comment]
i also have same issue today but after doing all these things mine not working.. Anyone could help me..

**Comment by daniel-rububura** [comment]
For latest MAC update to macOS Sequoia 15.1 seems to have problem with pgAdmin. For me this solution worked
1. Uninstalled existing postgres and downloaded latest postgres version
2. Upon installation of new version, uncheck the pgAdmin from items to be installed
3. After postgres installation completes, download pgAdmin from [https://www.pgadmin.org/download/pgadmin-4-macos/](https://www.pgadmin.org/download/pgadmin-4-macos/ )  and select latest release supported by Sequoia 15
4. Proceed with installation and it works fine not error is displayed

**Comment by moharanasudipt** [comment]
Okay I will try & let u check what the issue or what

**Comment by sandeep-edb** [comment]
Hi, this has been reported by other users on 15.1.  We are checking.

**Comment by moharanasudipt** [comment]
Ok, thanks for the update. & Mine issue was solved thank you.

**Comment by ankushkushwaha** [comment]
Worked
