### ISSUE TITLE
pgAgent is no longer provided with install

### ISSUE THREAD

**Issue by jaszej** [EnterpriseDB/edb-installers#187]
Upon having done a clean install of [PostgreSQL 17.0](https://sbp.enterprisedb.com/getfile.jsp?fileid=1259174) I am unable to find pgAgent option in Application Stack Builder, only pgBouncer is provided.

Tested on machine running Windows Server 2019 as well as another one running Windows 11 Pro (23H2).

**Comment by sandeep-edb** [comment]
Yeah, we haven't yet uploaded the pgAgent installer for PG17 on Windows. Should be done in a day or two

**Comment by sandeep-edb** [comment]
the installer is now available in StackBuilder
