### ISSUE TITLE
macOS cluster initialization failed 

### ISSUE THREAD

**Issue by maximusnet** [EnterpriseDB/edb-installers#194]
When installing, this error appears. And then it doesn’t work.
EDB installers 16.4-1
MAC OS 14.7.1 M1PRO
![2024-11-12_20-21-03](https://github.com/user-attachments/assets/380f2b59-5a2f-49d7-a0cf-804efa005449)
![2024-11-12_20-29-24](https://github.com/user-attachments/assets/d7a1f476-e298-403b-961e-0c359d5a9041)

**Comment by sandeep-edb** [comment]
please share the installation log that must have created in /tmp/

**Comment by sandeep-edb** [comment]
not enough information to debug the issue. closing the issue. feel free to open a new one if the issue persists in the latest available version
