### ISSUE TITLE
Issue with opening  PgAdmin 4 in Mac OS after upgrading OS system to Sequoia 15.1 [ error = _LSOpenURLsWithCompletionHandler() failed with error -54. (1) ]

### ISSUE THREAD

**Issue by gutieo** [EnterpriseDB/edb-installers#198]
I see the following error message:

_LSOpenURLsWithCompletionHandler() failed with error -54. (1)

Before upgrading my MAC OS to Sequoia 15.1,  PostgresSQL 17 was running without issues. 

Using the graphical interphase, I installed Postgre SQL version 17.1 for Mac OS X.

My machine is Mac Mini Apple M2 Pro.

Thank you in advance for any advice.

Best,
O

**Comment by sandeep-edb** [comment]
Hi, this has been reported by other users on 15.1.  We are checking.

**Comment by cbm27** [comment]
hi

**Comment by sandeep-edb** [comment]
@gutieo The PostgreSQL 17.2 is out if you can try installing and confirm if the issue is fixed
