### ISSUE TITLE
How to silently install postgresql-17.2-2-windows-x64.exe in WPF framework ?

### ISSUE THREAD

**Issue by roxxxxssss** [EnterpriseDB/edb-installers#215]
hello, I want to silently install postgresql-17.2-2-windows-x64.exe in the WPF framework using C # language, but, I couldn't find the relevant silent installation parameters. Could you please help me? Thank you.

**Comment by roxxxxssss** [comment]
I have found a solution, thank you everyone

**Comment by sandeep-edb** [comment]
Hi,

The silent/unattended installation can be achieved using the command line option _--mode unattended_. Along with this you may also use _--unattendedmodeui none_ to suppress the progress bar as well

You can also use _--optionfile_ option to define the inputs as key/value pair. This is suggested if you want to use the non-default values

**Comment by roxxxxssss** [comment]
thank you very much.
