### ISSUE TITLE
Malware detected in installers

### ISSUE THREAD

**Issue by devguilhermy** [EnterpriseDB/edb-installers#61]
Hello!

I uploaded the last 4 versions of Postgres EDB for Windows (14.5, 13.8, 12.12, 11.17) to VirusTotal and it found malware in all of them. 
I am not sure if this is actual or just a false-positive, but it's worth checking out and fixing it.

Here is a screenshot of the results of scanning the last version
![image](https://user-images.githubusercontent.com/55157846/185611212-b211ceca-add0-46a8-8d38-331bd1c2829e.png)

Here are the links for the results:
v14.5 - https://www.virustotal.com/gui/file/e91b3aa882a0af54fda36043f492252e472c878904e2c3d92e6c799c33e75dea
v13.8 - https://www.virustotal.com/gui/file/9617034515737339b3ff1c7ad091312ef5beb16d123cd030b2ecb3091b4ddfb9
v12.12 - https://www.virustotal.com/gui/file/065b33587807c954d88738304967d7d845f76d289a5e972ef11bfb6855634df0
v11.17 - https://www.virustotal.com/gui/file/7c53cb6dcc688a92b2e29bbbc6d1799ae268855e18c65ae399b05dd7d69f630f

Cheers!

**Comment by Semab-Tariq** [comment]
Hi @devguilhermy 

In our investigation, it seems like InstallBuilder's latest version has to do something with these virus reports we are in touch with the InstallBuidler support team and hopefully it will be fixed soon

Thanks for reporting this issue

**Comment by sandeep-edb** [comment]
Hi,
Thanks for your patience. This has taken more time than expected. But we are happy to share that all the Antivirus vendors have marked the reports issues as 'false-positives' and cleared them.

**Comment by devguilhermy** [comment]
This is great, thanks for looking into this and for the update! 
Cheers! 🙂

**Comment by lukadules-ship-it** [comment]
Not completed
