### ISSUE TITLE
Application list download reports malware

### ISSUE THREAD

**Issue by thecircleoflifefree** [EnterpriseDB/edb-installers#70]
On windows machine the following warning appears:

" A certificateverification problem was encountered whilst accessing https://www.postgresql.org/applications-v2.xml schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
This means that the source of the download cannot be verified. It is recommended that you do not continue with the download as it may be coming from a site that is pretending to be the intended download site and may contain viruses or malware. "

![image](https://user-images.githubusercontent.com/26904626/200135190-9e0ade26-6491-4653-9519-b49cd73eb928.png)

Kindly advise.

**Comment by thecircleoflifefree** [comment]
When clicking on yes the following is displayed:

![image](https://user-images.githubusercontent.com/26904626/200139148-741f6a72-0059-46e8-bc15-2e71d611efbe.png)

**Comment by dpage-edb** [comment]
Apologies for missing this. I assume the issue was resolved - if not, please log a new issue.
