### ISSUE TITLE
Typo in the French translation

### ISSUE THREAD

**Issue by nick-ivanov-edb** [EnterpriseDB/edb-installers#71]
The variable name `superaccount` is misspelled in https://github.com/EnterpriseDB/edb-installers/blob/b58f7e1474f33ed2943c28bf223b909b3972ee79/server/i18n/fr.lng#L63

**Comment by nick-ivanov-edb** [comment]
I see it's already fixed in the master branch.

**Comment by nick-ivanov-edb** [comment]
Oh, "master" is not the development branch? The problem is [still present](https://github.com/EnterpriseDB/edb-installers/blob/02bbbe75273f6ddb0c6388b3e919b101170b6a36/server/i18n/fr.lng#L63) in REL-15. To which branch should I submit a pull request?

**Comment by dpage** [comment]
Please submit to the REL-16 branch. Thanks.

**Comment by sandeep-edb** [comment]
please submit the PR to the REL-16 branch and we'll cherry-pick to the back branches. Thanks

**Comment by nick-ivanov-edb** [comment]
https://github.com/EnterpriseDB/edb-installers/pull/121

**Comment by dpage-edb** [comment]
This was merged.
