### ISSUE TITLE
Language Pack missing from StackBuilder (PostgreSQL 15.3)

### ISSUE THREAD

**Issue by anthonydb** [EnterpriseDB/edb-installers#80]
While installing a fresh copy of PostgreSQL 15.3 for Windows (community version) downloaded from the EDB website, I have discovered that the Language Pack usually present in StackBuilder is missing. 

Is this a temporary or a permanent change?

**Comment by sandeep-edb** [comment]
@anthonydb this should be fixed now. The latest version of LanguagePack v3 (3.1-1) is now available in StackBuilder for Windows. Sorry for the inconvenience caused

**Comment by anthonydb** [comment]
Thank you!
