### ISSUE TITLE
Remove directories and related config info for unsupported packages.

### ISSUE THREAD

**Issue by dpage** [EnterpriseDB/edb-installers#97]
For example, Slony and pgMemcache are no longer supported, yet we still seem to have code for them in the v16 branch.

Please remove code for anything that is not supported in all active branches.

**Comment by sandeep-edb** [comment]
Removed the directories and the configs for the unsupported components on the active branches 12 to 16. The decoupled components like pgbouncer and connectors are being built on REL-15

**Comment by sandeep-edb** [comment]
committed the fix on all supported branches
